// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7zRiD1k8TdCDdMaDjqpu5zemJjTNszaI',
    appId: '1:648228007298:web:ce07e2b3151aaf3498b39b',
    messagingSenderId: '648228007298',
    projectId: 'to-do-list-123-6b267',
    authDomain: 'to-do-list-123-6b267.firebaseapp.com',
    storageBucket: 'to-do-list-123-6b267.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa61MmIM79Rno0EbRsz5Ij77dq-0RhQnU',
    appId: '1:648228007298:android:8cbf2336ab261eb698b39b',
    messagingSenderId: '648228007298',
    projectId: 'to-do-list-123-6b267',
    storageBucket: 'to-do-list-123-6b267.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkUn8nqRRV18NbF4u8YxiQyylBXPMWP4A',
    appId: '1:648228007298:ios:688ee676fed0f89b98b39b',
    messagingSenderId: '648228007298',
    projectId: 'to-do-list-123-6b267',
    storageBucket: 'to-do-list-123-6b267.appspot.com',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkUn8nqRRV18NbF4u8YxiQyylBXPMWP4A',
    appId: '1:648228007298:ios:688ee676fed0f89b98b39b',
    messagingSenderId: '648228007298',
    projectId: 'to-do-list-123-6b267',
    storageBucket: 'to-do-list-123-6b267.appspot.com',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7zRiD1k8TdCDdMaDjqpu5zemJjTNszaI',
    appId: '1:648228007298:web:ef620804f7e5bf0598b39b',
    messagingSenderId: '648228007298',
    projectId: 'to-do-list-123-6b267',
    authDomain: 'to-do-list-123-6b267.firebaseapp.com',
    storageBucket: 'to-do-list-123-6b267.appspot.com',
  );
}
