// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB64W-QIffQs1J1MtSUW7zxNd0nIfyCXLA',
    appId: '1:1069939831484:web:09492bd5938848bfa756b9',
    messagingSenderId: '1069939831484',
    projectId: 'to-do-list-145b7',
    authDomain: 'to-do-list-145b7.firebaseapp.com',
    storageBucket: 'to-do-list-145b7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHyX3gWa7H6yx_DgIWI18BPQGMZo9BTnE',
    appId: '1:1069939831484:android:46cab1523e22ee7fa756b9',
    messagingSenderId: '1069939831484',
    projectId: 'to-do-list-145b7',
    storageBucket: 'to-do-list-145b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg_vLM4XYI2XLXuqF_BccrswKSlk-SqTI',
    appId: '1:1069939831484:ios:68f5e866a1f803b2a756b9',
    messagingSenderId: '1069939831484',
    projectId: 'to-do-list-145b7',
    storageBucket: 'to-do-list-145b7.appspot.com',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg_vLM4XYI2XLXuqF_BccrswKSlk-SqTI',
    appId: '1:1069939831484:ios:fe68550a1cb4e68fa756b9',
    messagingSenderId: '1069939831484',
    projectId: 'to-do-list-145b7',
    storageBucket: 'to-do-list-145b7.appspot.com',
    iosBundleId: 'com.example.toDoList.RunnerTests',
  );
}
